"""Hot-spot PATCH endpoint for initiative turn/round advancement, backed by
the SQLite initiative_state table. This is the highest-frequency, most
contested action in a live session (advancing turns) and previously had NO
server-side version check at all on its full-file save — see the discovery
notes in the rework plan. Now goes through a real DB transaction plus a
write-through mirror to Initiative Tracker.md, matching the pattern used for
sheet vitals (routes_sheets.py) and battlemap tokens (routes_battlemap.py).
"""
from __future__ import annotations

import re

from flask import request, jsonify

import db
import resource_cache
from frontend_api import bp
from sheet_helpers import REPO_ROOT, get_player_root_base


def _serialize_tracker_markdown(state: dict) -> str:
    """Rebuild Initiative Tracker.md's markdown from the current DB state."""
    order = state.get('order') or []
    lines = [
        '| Character | Initiative | Enemy | Manual HP | Damage Mode |',
        '| --------- | ---------: | :---: | :-------: | :---------: |',
    ]
    for entry in order:
        name = entry.get('name', '')
        initiative = entry.get('initiative', '')
        enemy = 'x' if entry.get('isEnemy') else ''
        manual_hp = entry.get('manualCurrentHp') or ''
        damage_mode = entry.get('damageMode') or ''
        lines.append(f"| {name} | {initiative} | {enemy} | {manual_hp} | {damage_mode} |")
    lines.append('| End of Round | 0 | | | |')

    current_turn_index = state.get('currentTurnIndex', 0)
    current_name = order[current_turn_index]['name'] if 0 <= current_turn_index < len(order) else ''
    lines.append('')
    lines.append(f"**Current Turn:** {current_name} (Index: {current_turn_index})")
    lines.append(f"**Round:** {state.get('roundNumber', 1)}")
    lines.append('')
    lines.append('_Last generated by Mycelium/scripts/Python/rebuild_database.py (write-through)_')
    return '\n'.join(lines) + '\n'


@bp.route('/api/initiative/turn', methods=['PATCH'])
def patch_initiative_turn():
    """Advance/adjust turn+round state (and optionally per-combatant HP
    deltas) under a real DB transaction instead of a whole-file overwrite
    with no version check.

    Body: { expected_version?: int, currentTurnIndex?, roundNumber?,
             characters?: [{name, currentHp}] }
    """
    data = request.get_json() or {}
    expected_version = data.get('expected_version')
    fields = {}
    for key in ('currentTurnIndex', 'roundNumber', 'characters'):
        if key in data:
            fields[key] = data[key]
    if not fields:
        return jsonify(error='No recognized fields provided'), 400

    try:
        new_state = db.update_initiative_state(expected_version, fields)
    except db.VersionConflict as vc:
        return jsonify(error='Version conflict', current=vc.current), 409
    except Exception as e:
        return jsonify(error=str(e)), 500

    tracker_path = get_player_root_base() / 'Initiative Tracker.md'
    try:
        new_text = _serialize_tracker_markdown(new_state)
        resource_cache.write_with_version_check(
            tracker_path, new_text, expected_version=None,
            publish_path=str(tracker_path.relative_to(REPO_ROOT).as_posix()) if tracker_path.exists() else 'Player Root/Initiative Tracker.md',
        )
    except Exception as e:
        new_state['mirrorWarning'] = str(e)

    return jsonify(success=True, initiative=new_state)


@bp.route('/api/initiative', methods=['GET'])
def get_initiative_state():
    """Return the current DB-backed initiative state (for clients that want
    to bootstrap without parsing the markdown themselves)."""
    state = db.get_initiative_state()
    if state is None:
        return jsonify(error='No initiative state found; run rebuild_database.py'), 404
    return jsonify(state)
