#!/usr/bin/env python3
"""add_folder_tag.py

Add a tag (hashtag) derived from a folder's name to all markdown files in
that folder. Use --recursive to include files in subdirectories.

Usage:
  python3 add_folder_tag.py <folder> [--recursive] [--dry-run] [--verbose]

Behavior:
 - The tag is generated by slugifying the folder name: lowercased, spaces
   replaced with underscores, and non [a-z0-9_-] removed.
 - If the tag is already present in a file (either in a 'tags:' line or as
   an inline hashtag), the file is skipped.
 - By default the script appends the '#tag' to the end of the file (new line).
   This is robust and doesn't attempt complex YAML/frontmatter edits.
"""
from __future__ import annotations
from pathlib import Path
import argparse
import re
from typing import List

MD_EXTS = {'.md', '.markdown'}


def slugify(name: str) -> str:
    s = name.strip().lower()
    s = re.sub(r'\s+', '_', s)
    s = re.sub(r'[^a-z0-9_-]', '', s)
    if not s:
        s = 'tag'
    return s


def iter_md_files(folder: Path, recursive: bool) -> List[Path]:
    out = []
    if recursive:
        for p in folder.rglob('*'):
            try:
                if p.is_file() and p.suffix.lower() in MD_EXTS:
                    out.append(p.resolve())
            except Exception:
                continue
    else:
        try:
            for p in folder.iterdir():
                try:
                    if p.is_file() and p.suffix.lower() in MD_EXTS:
                        out.append(p.resolve())
                except Exception:
                    continue
        except Exception:
            pass
    return out


def has_tag(txt: str, tag: str) -> bool:
    # check tags: YAML-like
    m = re.search(r'^\s*tags:\s*(.+)$', txt, flags=re.MULTILINE)
    if m:
        if re.search(r'\b' + re.escape(tag) + r'\b', m.group(1)):
            return True
    # check inline hashtags
    if re.search(r'#' + re.escape(tag) + r'\b', txt):
        return True
    return False


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description='Add folder-name tag to markdown files')
    ap.add_argument('folder', help='Folder path to operate on (repo-relative or absolute)')
    ap.add_argument('--recursive', '-r', action='store_true', help='Also process subdirectories')
    ap.add_argument('--dry-run', action='store_true', help="Don't modify files; just show what would change")
    ap.add_argument('--verbose', '-v', action='store_true', help='Verbose output')
    args = ap.parse_args(argv)

    folder = Path(args.folder)
    if not folder.exists():
        print(f"Folder not found: {folder}")
        return 2
    if not folder.is_dir():
        print(f"Not a folder: {folder}")
        return 2

    tag_base = slugify(folder.name)
    tag = tag_base
    files = iter_md_files(folder, args.recursive)
    if args.verbose:
        print(f"Found {len(files)} markdown files in {folder} (recursive={args.recursive})")

    modified = 0
    modified_paths: List[Path] = []
    for p in sorted(files):
        try:
            txt = p.read_text(encoding='utf-8')
        except Exception:
            if args.verbose:
                print(f"Skipping unreadable file: {p}")
            continue
        if has_tag(txt, tag):
            if args.verbose:
                print(f"Already tagged: {p}")
            continue
        if args.dry_run:
            print(f"Would tag: {p} -> #{tag}")
            modified += 1
            modified_paths.append(p)
            continue
        # append the tag at the end of the file on its own line
        try:
            new_txt = txt.rstrip() + "\n\n#" + tag + "\n"
            p.write_text(new_txt, encoding='utf-8')
            modified += 1
            modified_paths.append(p)
            if args.verbose:
                print(f"Tagged: {p} -> #{tag}")
        except Exception as e:
            print(f"Failed to write {p}: {e}")

    # Short summary
    action = 'would be tagged' if args.dry_run else 'tagged'
    print('\n--- Summary ---')
    print(f"Folder: {folder}")
    print(f"Tag: #{tag}")
    print(f"Recursive: {args.recursive}")
    print(f"Mode: {'dry-run' if args.dry_run else 'apply'}")
    print(f"Files {action}: {modified}")
    if modified_paths:
        print('Sample files:')
        for p in modified_paths[:5]:
            print(f" - {p}")
        if len(modified_paths) > 5:
            print(f" - ...and {len(modified_paths)-5} more")
    print('--- End Summary ---')
    return 0
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
