#!/usr/bin/env python3
"""Packaged helper: create_npc

Minimal canonical implementation for NPC creation, reusing the same
config lookup and patterns as create_pc helper.
"""
from __future__ import annotations
import argparse
from pathlib import Path
from .config_loader import get_config
import sys


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument('--name', required=True, help='NPC name')
    p.add_argument('--out-root', default=get_config('npcs_root', 'DMs Part/NPCs'))
    args = p.parse_args(argv)

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    filename = f"{args.name} NPC Sheet.md"
    fpath = out_root / filename
    # basic placeholder content
    content = f"# {args.name}\n\nThis is an NPC sheet generated by create_npc helper.\n"
    fpath.write_text(content, encoding='utf-8')
    print(f"Wrote NPC sheet: {fpath}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
#!/usr/bin/env python3
"""Packaged helper: create_npc

Near-copy of the top-level `create_npc.py` but imports `get_config`
from the package-local config loader (from .config_loader import get_config).
"""
from __future__ import annotations
import argparse
import subprocess
from pathlib import Path
import sys
import re
from .config_loader import get_config

# ...existing TEMPLATE and functions copied from original create_npc.py...

def main(argv: list[str] | None = None) -> int:
    # delegate to original implementation (copied into this helper file)
    # ...existing code...
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
