#!/usr/bin/env python3
"""
Generate an initiative tracker for combat encounters.

Reads character names from Player Root/pc_primary_stats.md.
Prompts for initiative values via command line.
Press Enter without a value to skip a character.
Creates: Player Root/PCs/Initiative Tracker.md with sorted initiative order (highest first).

Usage:
    python generate_initiative.py          # Create new initiative tracker
    python generate_initiative.py --edit   # Edit existing tracker (update one character)
"""
from pathlib import Path
import re
import sys
import argparse


REPO_ROOT = Path(__file__).resolve().parents[3]
PLAYER_ROOT = REPO_ROOT / "Player Root"
PC_DIR = PLAYER_ROOT / "PCs"
PC_STATS_FILE = PLAYER_ROOT / "pc_primary_stats.md"
OUT_FILE = PC_DIR / "Initiative Tracker.md"


def read_character_names():
    """
    Read character names from pc_primary_stats.md.
    Extracts names from wiki links like [[Name]] in the table.
    Returns a list of character names.
    """
    if not PC_STATS_FILE.exists():
        print(f"Warning: {PC_STATS_FILE} not found.")
        return []
    
    try:
        content = PC_STATS_FILE.read_text(encoding="utf-8")
    except Exception as e:
        print(f"Error reading {PC_STATS_FILE}: {e}")
        return []
    
    names = []
    # Match wiki links like [[Name]] in table rows
    for line in content.splitlines():
        # Skip header rows and empty lines
        if not line.strip() or line.strip().startswith("|") and "Name" in line and "STR" in line:
            continue
        
        # Find wiki links [[...]]
        matches = re.findall(r'\[\[([^\]]+)\]\]', line)
        for match in matches:
            # Clean up any extra whitespace
            name = match.strip()
            if name and name not in names:
                names.append(name)
    
    return names


def get_initiative_input():
    """
    Prompt for initiative values for each character from pc_primary_stats.md,
    then prompt for additional characters (like enemies).
    Press Enter without a value to skip a character.
    Returns a list of (name, initiative) tuples.
    """
    print("=== Initiative Tracker ===")
    print("Reading character names from pc_primary_stats.md...")
    
    names = read_character_names()
    
    if not names:
        print("No character names found in pc_primary_stats.md")
        print("Please ensure the file exists and contains character names in [[brackets]].\n")
    else:
        print(f"Found {len(names)} character(s).")
        print("Enter initiative value for each character.")
        print("Press Enter without a value to skip that character.\n")
    
    entries = []
    
    # First, go through PC characters from the file
    for name in names:
        try:
            init_str = input(f"Initiative for {name}: ").strip()
            
            if not init_str:
                print(f"  (skipped {name})")
                continue
            
            try:
                initiative = int(init_str)
                entries.append((name, initiative))
                print(f"  ✓ Added {name} with initiative {initiative}")
            except ValueError:
                print(f"  (skipped {name} - '{init_str}' is not a valid number)")
                
        except (EOFError, KeyboardInterrupt):
            print("\n\nInterrupted. Exiting...")
            sys.exit(0)
    
    # Now prompt for additional characters (enemies, etc.)
    print("\n--- Additional Characters (enemies, NPCs, etc.) ---")
    print("Enter character name and initiative.")
    print("Press Enter without a name to finish.\n")
    
    while True:
        try:
            name = input("Character name (or press Enter to finish): ").strip()
            
            if not name:
                break
            
            init_str = input(f"  Initiative for {name}: ").strip()
            
            if not init_str:
                print(f"  (skipped {name} - no initiative provided)")
                continue
            
            try:
                initiative = int(init_str)
                entries.append((name, initiative))
                print(f"  ✓ Added {name} with initiative {initiative}")
            except ValueError:
                print(f"  (skipped {name} - '{init_str}' is not a valid number)")
                
        except (EOFError, KeyboardInterrupt):
            print("\n\nInterrupted. Exiting...")
            sys.exit(0)
    
    return entries


def render_markdown(entries):
    """
    Generate markdown content with sorted initiative table.
    Entries should be list of (name, initiative) tuples.
    """
    lines = []
    
    if not entries:
        lines.append("No characters entered.\n")
        lines.append("\n_Last generated by Mycelium/scripts/Python/generate_initiative.py_\n")
        return "\n".join(lines)
    
    # Sort by initiative (descending - highest first)
    sorted_entries = sorted(entries, key=lambda x: x[1], reverse=True)
    
    lines.append("| Character | Initiative |")
    lines.append("| --------- | ---------: |")
    
    for name, initiative in sorted_entries:
        lines.append(f"| {name} | {initiative} |")
    
    lines.append("\n_Last generated by Mycelium/scripts/Python/generate_initiative.py_\n")
    return "\n".join(lines)


def read_existing_tracker():
    """
    Read existing Initiative Tracker.md and parse character names and initiatives.
    Returns a list of (name, initiative) tuples, or None if file doesn't exist.
    """
    if not OUT_FILE.exists():
        return None
    
    try:
        content = OUT_FILE.read_text(encoding="utf-8")
    except Exception as e:
        print(f"Error reading {OUT_FILE}: {e}")
        return None
    
    entries = []
    # Parse table rows like: | Character Name | 15 |
    for line in content.splitlines():
        # Skip header, separator, and non-table lines
        if not line.strip().startswith("|") or "Character" in line or "---" in line:
            continue
        
        parts = [p.strip() for p in line.split("|") if p.strip()]
        if len(parts) >= 2:
            name = parts[0]
            try:
                initiative = int(parts[1])
                entries.append((name, initiative))
            except ValueError:
                continue
    
    return entries


def edit_initiative():
    """
    Edit mode: Read existing tracker, prompt for character to update, and save.
    """
    print("=== Edit Initiative Tracker ===")
    
    entries = read_existing_tracker()
    
    if not entries:
        print(f"No existing tracker found at {OUT_FILE}")
        print("Please create a tracker first by running without --edit flag.")
        sys.exit(1)
    
    print(f"Found {len(entries)} character(s) in existing tracker:\n")
    
    # Display current initiatives
    sorted_entries = sorted(entries, key=lambda x: x[1], reverse=True)
    for name, init in sorted_entries:
        print(f"  {name}: {init}")
    
    print()
    
    # Prompt for character to update
    try:
        char_name = input("Enter character name to update: ").strip()
        
        if not char_name:
            print("No character name provided. Exiting.")
            sys.exit(0)
        
        # Find character (case-insensitive)
        found_idx = None
        for idx, (name, init) in enumerate(entries):
            if name.lower() == char_name.lower():
                found_idx = idx
                break
        
        if found_idx is None:
            print(f"Character '{char_name}' not found in tracker.")
            print("Available characters:", ", ".join([n for n, _ in entries]))
            sys.exit(1)
        
        old_init = entries[found_idx][1]
        new_init_str = input(f"New initiative for {entries[found_idx][0]} (current: {old_init}): ").strip()
        
        if not new_init_str:
            print("No initiative provided. Exiting without changes.")
            sys.exit(0)
        
        try:
            new_init = int(new_init_str)
            entries[found_idx] = (entries[found_idx][0], new_init)
            print(f"✓ Updated {entries[found_idx][0]}: {old_init} → {new_init}")
        except ValueError:
            print(f"'{new_init_str}' is not a valid number. Exiting without changes.")
            sys.exit(1)
        
    except (EOFError, KeyboardInterrupt):
        print("\n\nInterrupted. Exiting without changes.")
        sys.exit(0)
    
    return entries


def main():
    """CLI entry point to create or edit the initiative tracker markdown."""
    parser = argparse.ArgumentParser(description="Generate or edit initiative tracker")
    parser.add_argument("--edit", action="store_true", help="Edit existing tracker (update one character)")
    args = parser.parse_args()
    
    if args.edit:
        entries = edit_initiative()
    else:
        entries = get_initiative_input()
    
    if not entries:
        print("\nNo characters to track. Exiting without creating file.")
        sys.exit(0)
    
    md = render_markdown(entries)
    
    try:
        OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        OUT_FILE.write_text(md, encoding="utf-8")
        print(f"\n✓ Wrote {OUT_FILE}")
        print(f"  Tracked {len(entries)} character(s)")
    except Exception as e:
        print(f"\nFailed to write output: {e}", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
